# Generated by Django 5.0.7 on 2024-07-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_name', models.CharField(max_length=100)),
                ('shoe_description', models.CharField(max_length=100)),
                ('shoe_price', models.IntegerField()),
                ('shoe_image', models.ImageField(upload_to='img')),
            ],
        ),
    ]
