# Generated by Django 5.0.7 on 2024-07-27 10:34

from django.db import migrations


def associate_cart_items(apps, schema_editor):
    Cart = apps.get_model('home', 'Cart')
    CartItem = apps.get_model('home', 'CartItem')
    User = apps.get_model('auth', 'User')

    for cart_item in CartItem.objects.filter(cart__isnull=True):
        cart, created = Cart.objects.get_or_create(user=cart_item.user)
        cart_item.cart = cart
        cart_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_cartitem_complete_and_more'),
    ]

    operations = [
        migrations.RunPython(associate_cart_items),
    ]
