# Generated by Django 5.0.7 on 2024-07-27 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_associate_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='complete',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='transaction_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.cart'),
            preserve_default=False,
        ),
    ]
