# Generated by Django 5.0.7 on 2024-07-27 11:37

from django.db import migrations,models
from home.models import CartItem

def set_default_cart(apps, schema_editor):
    Cart = apps.get_model('home', 'Cart')
    CartItem = apps.get_model('home', 'CartItem')
    User = apps.get_model('auth', 'User')

    for cart_item in CartItem.objects.filter(cart__isnull=True):
        user = cart_item.user
        if user:
            cart, created = Cart.objects.get_or_create(user=user)
            cart_item.cart = cart
            cart_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cartitem_complete_cartitem_transaction_id_and_more'),
    ]

    operations = [
         migrations.RunPython(CartItem),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(related_name='items', on_delete=models.CASCADE, to='home.Cart'),
        ),
    ]
